### ISSUE TITLE
Provide phar package for latest release  1.1.2

### ISSUE THREAD

**Issue by chadyred** [mayflower/PHP_CodeBrowser#46]
Hello,

Can you just provide a PHAR file please for the latest release it will be good !

**Comment by glensc** [comment]
https://github.com/Mayflower/PHP_CodeBrowser/releases

also the release title should be edited from `Symfony 3 compat + Bugfixes` to `1.1.2`

maintainer do it from `edit` button from here:
https://github.com/mayflower/PHP_CodeBrowser/releases/tag/1.1.2

**Comment by chadyred** [comment]
Thanks !

**Comment by glensc** [comment]
@chadyred why did you close this? i do not see anything done by maintainers

**Comment by calbrecht** [comment]
Sorry. I am going to do better now. 
There is a new release 1.1.3 including fixes and a phar file available https://github.com/mayflower/PHP_CodeBrowser/releases/tag/1.1.3

**Comment by chadyred** [comment]
Well, nice ! :)
