### ISSUE TITLE
Warning with PHP 7.1

### ISSUE THREAD

**Issue by tacman** [mayflower/PHP_CodeBrowser#47]
PHP 7.1 throws a warning when adding a string:

PHP Warning:  A non-numeric value encountered in /data/workspace/Codecheck/vendor/mayflower/php-codebrowser/templates/index.tpl on line 88

    $counts = array_fill_keys($occuringErrorTypes, ''); // <- should be 0, not blank

    foreach ($f->getIssues() as $issue) {
        $counts[$issue->foundBy] += 1; // otherwise, this throws a warning
    }

I'll submit a pull request

**Comment by fpletz** [comment]
Fixed by #48.
