### ISSUE TITLE
error in phar

### ISSUE THREAD

**Issue by garak** [mayflower/PHP_CodeBrowser#69]
Steps to reproduce:
* download [phpcb-2.2.phar](https://github.com/mayflower/PHP_CodeBrowser/releases/download/2.2/phpcb-2.2.phar)
* execute `php phpcb-2.2.phar`
* see error

>PHP Warning:  require(phar:///phpcb-2.2.phar/vendor/composer/../nette/di/src/compatibility.php): failed to open stream: phar error: "vendor/nette/di/src/compatibility.php" is not a file in phar "/phpcb-2.2.phar" in phar:////phpcb-2.2.phar/vendor/composer/autoload_real.php on line 66
PHP Fatal error:  require(): Failed opening required 'phar:////phpcb-2.2.phar/vendor/composer/../nette/di/src/compatibility.php' (include_path='.:/usr/share/php') in phar:////phpcb-2.2.phar/vendor/composer/autoload_real.php on line 66

**Comment by garak** [comment]
@mmoll maybe you can check for this?

**Comment by mmoll** [comment]
@garak Please check v2.3, it uses a new phar builder which fixed the problem at least for me locally.

**Comment by garak** [comment]
2.3 seems to work at start, but then... :disappointed: 
>Warning: include(phar:///home/circleci/app/bin/phpcb/templates/review.tpl): failed to open stream: phar error: "templates/review.tpl" is not a file in phar "/home/circleci/app/bin/phpcb" in phar:///home/circleci/app/bin/phpcb/src/PHPCodeBrowser/View/ViewAbstract.php on line 348

**Comment by calbrecht** [comment]
@garak could you checkout and build the branch https://github.com/mayflower/PHP_CodeBrowser/tree/69-fix-phar-build with `composer install ; composer phar` and see if it works with the resulting phar?

**Comment by garak** [comment]
@calbrecht it works that way

**Comment by calbrecht** [comment]
Thanks for testing @garak there is a new release https://github.com/mayflower/PHP_CodeBrowser/releases/tag/2.3.1
