### ISSUE TITLE
just installed version 2.2 error with Deprecated: Array and string offset

### ISSUE THREAD

**Issue by Arametheus** [mayflower/PHP_CodeBrowser#70]
command I'm running
vendor/bin/phpcb -l ./build -s ./app -s ./public -s ./resources -s ./routes -s ./tests -o ./build/code-browser

this is in laravel 6.1 using php 7.4

PHP Deprecated:  Array and string offset access syntax with curly braces is deprecated in /vendor/mayflower/php-codebrowser/src/PHPCodeBrowser/View/ViewReview.php on line 434
PHP Stack trace:
PHP   1. {main}() /vendor/mayflower/php-codebrowser/bin/phpcb:0
PHP   2. PHPCodeBrowser\Application->run() /vendor/mayflower/php-codebrowser/bin/phpcb:57
PHP   3. PHPCodeBrowser\Application->doRun() /vendor/symfony/console/Application.php:148
PHP   4. PHPCodeBrowser\Application->doRunCommand() /vendor/symfony/console/Application.php:272
PHP   5. PHPCodeBrowser\Command\RunCommand->run() /vendor/symfony/console/Application.php:1011
PHP   6. PHPCodeBrowser\Command\RunCommand->execute() /vendor/symfony/console/Command/Command.php:255
PHP   7. PHPCodeBrowser\CLIController->run() /vendor/mayflower/php-codebrowser/src/PHPCodeBrowser/Command/RunCommand.php:194
PHP   8. spl_autoload_call() /vendor/mayflower/php-codebrowser/src/PHPCodeBrowser/CLIController.php:244
PHP   9. Composer\Autoload\ClassLoader->loadClass() /vendor/mayflower/php-codebrowser/src/PHPCodeBrowser/CLIController.php:244
PHP  10. Composer\Autoload\includeFile() /vendor/composer/ClassLoader.php:322

**Comment by mmoll** [comment]
Should be fixed with v2.3.

**Comment by mmoll** [comment]
Should be fixed with v2.3.
