### ISSUE TITLE
v2.3.1 not compatible with phpunit 9.x

### ISSUE THREAD

**Issue by PEM-FR** [mayflower/PHP_CodeBrowser#72]
Hello,

In CodeBrowser's composer.json there is a 
phpunit/php-file-iterator: ~2.0

while in phpunit 9.x there is a 
phpunit/php-file-iterator: ^3.0

Do you think this one could be bumped?

Best regards :)

**Comment by tezhm** [comment]
Any update on this?

**Comment by calbrecht** [comment]
Thanks for notifying :) Indeed. https://github.com/mayflower/PHP_CodeBrowser/releases/tag/2.4.0
