### ISSUE TITLE
Missing support for php8

### ISSUE THREAD

**Issue by garak** [mayflower/PHP_CodeBrowser#74]

**Comment by calbrecht** [comment]
Well, `phpcs` and `phpstan` are fighting over `unused parameters` vs. `implement interface`. And then, there are still the issues with `DOMNode::getAttribute()` which, in fact is a whole lot of another problem...

**Comment by calbrecht** [comment]
To elaborate: `DOMNode` itself does not have the method `getAttribute()`, but `DOMElement`, which inherits from `DOMNode` does have it. So, probably a lot of files have to be refactored.

**Comment by calbrecht** [comment]
Ok, did it quick'n'dirty :=

**Comment by calbrecht** [comment]
https://github.com/mayflower/PHP_CodeBrowser/releases/tag/3.0.0
