### ISSUE TITLE
Not PHP 8.1 compatible

### ISSUE THREAD

**Issue by markdwhite** [mayflower/PHP_CodeBrowser#79]
For example, where extended classes now have type hinted properties:

PHP Fatal error:  Type of PHPCodeBrowser\IssueXML::$formatOutput must be bool (as in class DOMDocument) 

Ummm...seems like a short issue, but what else do you need?

**Comment by calbrecht** [comment]
Oh sorry @markdwhite and @garak, it happens now and then that my focus is not on reading github notifications :)
Sure @garak go ahead :+1:

**Comment by mmoll** [comment]
This should be fixed with 3.0.1, could you test and report back?

**Comment by garak** [comment]
> This should be fixed with 3.0.1, could you test and report back?

Just tried, and I got this:

```
Fatal error: Uncaught Error: Class "Symfony\Component\String\UnicodeString" not found in phar:///myapp/bin/phpcb/vendor/symfony/console/Helper/Helper.php:65
Stack trace:
#0 phar:///myapp/bin/phpcb/vendor/symfony/console/Application.php(871): Symfony\Component\Console\Helper\Helper::width('Log directory d...')
#1 phar:///myapp/bin/phpcb/vendor/symfony/console/Application.php(840): Symfony\Component\Console\Application->doRenderThrowable(Object(InvalidArgumentException), Object(Symfony\Component\Console\Output\StreamOutput))
#2 phar:///myapp/bin/phpcb/vendor/symfony/console/Application.php(154): Symfony\Component\Console\Application->renderThrowable(Object(InvalidArgumentException), Object(Symfony\Component\Console\Output\StreamOutput))
#3 phar:///myapp/bin/phpcb/vendor/symfony/console/Application.php(177): Symfony\Component\Console\Application->Symfony\Component\Console\{closure}(Object(InvalidArgumentException))
#4 phar:///myapp/bin/phpcb/bin/phpcb(56): Symfony\Component\Console\Application->run()
#5 /myapp/bin/phpcb(14): require('phar:///garak/g...')
#6 {main}
  thrown in phar:///myapp/bin/phpcb/vendor/symfony/console/Helper/Helper.php on line 65

```

**Comment by mmoll** [comment]
Thanks, 3.0.2 should fix that.

**Comment by garak** [comment]
It works, thank you!
The only minor question I can highlight is `Deprecated: Function utf8_encode() is deprecated in phar:///home/circleci/app/bin/phpcb/src/PHPCodeBrowser/View/ViewReview.php on line 368` (maybe it could be handled in a new issue)

**Comment by mmoll** [comment]
> `Function utf8_encode() is deprecated`

Yes, this is already part of #82

**Comment by mmoll** [comment]
4.0.0 got released and is PHP 8.x only, please test and report back here :bowtie:.

**Comment by garak** [comment]
> 4.0.0 got released and is PHP 8.x only, please test and report back here :bowtie:.

I tested it and it works flawlessly
Thank you!

**Comment by mmoll** [comment]
> I tested it and it works flawlessly

Thanks for testing!
